INFO: 2019-01-18 09:21:36,133: perform_upgrade() 'Last run version was 0.6.7 or earlier, current version is 0.6.7'
INFO: 2019-01-18 09:21:36,134: process_command() 'Received command: []'
INFO: 2019-01-18 09:21:36,153: load() 'Jumble loading'
INFO: 2019-01-18 09:21:36,154: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/__init__.py'
INFO: 2019-01-18 09:21:36,154: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/share/variety/plugins/quotes/LocalFilesSource.py'
INFO: 2019-01-18 09:21:36,154: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'author': 'Peter Levi', 'name': 'Local text files', 'version': '0.1', 'description': u'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt'}'
INFO: 2019-01-18 09:21:36,155: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/share/variety/plugins/quotes/GoodreadsSource.py'
INFO: 2019-01-18 09:21:36,161: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'author': 'Peter Levi', 'name': 'Goodreads', 'version': '0.1', 'description': u'Fetches quotes from Goodreads.com'}'
INFO: 2019-01-18 09:21:36,161: _walk_modules() 'Jumble loading module in QuotesDaddySource from /usr/share/variety/plugins/quotes/QuotesDaddySource.py'
INFO: 2019-01-18 09:21:36,161: load() 'Jumble found plugin class: <class 'QuotesDaddySource.QuotesDaddySource'>: {'author': 'Peter Levi', 'name': 'QuotesDaddy', 'version': '0.1', 'description': u"Fetches quotes from QuotesDaddy's daily quotes RSS feed.\nDoes not support searching by tags or authors."}'
INFO: 2019-01-18 09:21:36,161: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/quotes/__init__.py'
INFO: 2019-01-18 09:21:36,161: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/share/variety/plugins/quotes/QuotationsPageSource.py'
INFO: 2019-01-18 09:21:36,162: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'author': 'Peter Levi', 'name': 'TheQuotationsPage.com', 'version': '0.1', 'description': u'Fetches quotes from TheQuotationsPage.com'}'
INFO: 2019-01-18 09:21:36,165: reload_config() 'Creating new downloader for type 19, location Recommended by Variety. Adapts to your taste as you mark images as favorite or trash.'
ERROR: 2019-01-18 09:21:36,165: reload_config() 'Could not create Downloader for type 19, location Recommended by Variety. Adapts to your taste as you mark images as favorite or trash.'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 420, in reload_config
    dlr = self.create_downloader(type, location)
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 555, in create_downloader
    raise Exception('No Smart user yet, not a problem')
Exception: No Smart user yet, not a problem
INFO: 2019-01-18 09:21:36,166: reload_config() 'Creating new downloader for type 6, location Random wallpapers from Desktoppr.co'
INFO: 2019-01-18 09:21:36,166: reload_config() 'Creating new downloader for type 15, location Bing Photo of the Day'
INFO: 2019-01-18 09:21:36,167: reload_config() 'Creating new downloader for type 16, location High-resolution photos from Unsplash.com'
INFO: 2019-01-18 09:21:36,167: reload_config() 'Creating new downloader for type 8, location NASA's Astronomy Picture of the Day'
INFO: 2019-01-18 09:21:36,167: reload_config() 'Creating new downloader for type 7, location user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'
INFO: 2019-01-18 09:21:36,169: log_options() 'Loaded options:'
INFO: 2019-01-18 09:21:36,169: log_options() 'change_enabled = True'
INFO: 2019-01-18 09:21:36,169: log_options() 'change_interval = 300'
INFO: 2019-01-18 09:21:36,169: log_options() 'change_on_start = False'
INFO: 2019-01-18 09:21:36,169: log_options() 'clipboard_enabled = False'
INFO: 2019-01-18 09:21:36,169: log_options() 'clipboard_hosts = [u'wallhaven.cc', u'ns223506.ovh.net', u'wallpapers.net', u'flickr.com', u'imgur.com', u'deviantart.com', u'interfacelift.com', u'vladstudio.com', u'imageshack.us']'
INFO: 2019-01-18 09:21:36,169: log_options() 'clipboard_use_whitelist = True'
INFO: 2019-01-18 09:21:36,169: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2019-01-18 09:21:36,169: log_options() 'clock_enabled = False'
INFO: 2019-01-18 09:21:36,169: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2019-01-18 09:21:36,169: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2019-01-18 09:21:36,170: log_options() 'configfile = /home/fuzie/.config/variety/variety.conf'
INFO: 2019-01-18 09:21:36,170: log_options() 'copyto_enabled = True'
INFO: 2019-01-18 09:21:36,170: log_options() 'copyto_folder = Default'
INFO: 2019-01-18 09:21:36,170: log_options() 'desired_color = [160, 160, 160]'
INFO: 2019-01-18 09:21:36,170: log_options() 'desired_color_enabled = False'
INFO: 2019-01-18 09:21:36,170: log_options() 'download_enabled = True'
INFO: 2019-01-18 09:21:36,170: log_options() 'download_folder = /home/fuzie/.config/variety/Downloaded'
INFO: 2019-01-18 09:21:36,170: log_options() 'download_interval = 600'
INFO: 2019-01-18 09:21:36,170: log_options() 'facebook_message = '
INFO: 2019-01-18 09:21:36,170: log_options() 'facebook_show_dialog = True'
INFO: 2019-01-18 09:21:36,170: log_options() 'favorites_folder = /home/fuzie/Dropbox/Andet/Favorites'
INFO: 2019-01-18 09:21:36,170: log_options() 'favorites_operations = [[u'Downloaded', u'Copy'], [u'Fetched', u'Move'], [u'Others', u'Copy']]'
INFO: 2019-01-18 09:21:36,170: log_options() 'fetched_folder = /home/fuzie/.config/variety/Fetched'
INFO: 2019-01-18 09:21:36,170: log_options() 'filters = [[False, u'Keep original', u''], [False, u'Grayscale', u'-type Grayscale'], [False, u'Heavy blur', u'-blur 120x40'], [False, u'Soft blur', u'-blur 20x7'], [False, u'Oil painting', u'-paint 8'], [False, u'Pencil sketch', u'-colorspace gray \\( +clone -tile ~/.config/variety/pencil_tile.png -draw "color 0,0 reset" +clone +swap -compose color_dodge -composite \\) -fx \'u*.2+v*.8\''], [False, u'Pointilism', u'-spread 10 -noise 3'], [False, u'Pixellate', u'-scale 3% -scale 3333%']]'
INFO: 2019-01-18 09:21:36,170: log_options() 'icon = Current'
INFO: 2019-01-18 09:21:36,170: log_options() 'lightness_enabled = False'
INFO: 2019-01-18 09:21:36,170: log_options() 'lightness_mode = 0'
INFO: 2019-01-18 09:21:36,170: log_options() 'min_rating = 4'
INFO: 2019-01-18 09:21:36,170: log_options() 'min_rating_enabled = False'
INFO: 2019-01-18 09:21:36,171: log_options() 'min_size = 80'
INFO: 2019-01-18 09:21:36,171: log_options() 'min_size_enabled = False'
INFO: 2019-01-18 09:21:36,171: log_options() 'quota_enabled = True'
INFO: 2019-01-18 09:21:36,171: log_options() 'quota_size = 500'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_authors = '
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_bg_opacity = 55'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_change_enabled = False'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_change_interval = 300'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_disabled_sources = [u'QuotesDaddy']'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_enabled = False'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_favorites_file = /home/fuzie/.config/variety/favorite_quotes.txt'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_hpos = 100'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_tags = '
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_text_shadow = False'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_vpos = 40'
INFO: 2019-01-18 09:21:36,171: log_options() 'quotes_width = 70'
INFO: 2019-01-18 09:21:36,172: log_options() 'safe_mode = False'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_custom_enabled = False'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_custom_folder = /home/fuzie/Pictures'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_downloads_enabled = False'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_fade = 0.4'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_favorites_enabled = True'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_mode = Fullscreen'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_monitor = All'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_pan = 0.05'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_seconds = 6.0'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_sort_order = Random'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_sources_enabled = True'
INFO: 2019-01-18 09:21:36,172: log_options() 'slideshow_zoom = 0.2'
INFO: 2019-01-18 09:21:36,172: log_options() 'smart_enabled = True'
INFO: 2019-01-18 09:21:36,172: log_options() 'smart_notice_shown = True'
INFO: 2019-01-18 09:21:36,175: log_options() 'smart_register_shown = True'
INFO: 2019-01-18 09:21:36,175: log_options() 'sources = [[True, 3, u'The Favorites folder'], [True, 4, u'The Fetched folder'], [True, 19, u'Recommended by Variety. Adapts to your taste as you mark images as favorite or trash.'], [False, 20, u'Latest favorites by the other users of Variety. [May contain NSFW images]'], [True, 2, u'/usr/share/backgrounds'], [True, 6, u'Random wallpapers from Desktoppr.co'], [True, 15, u'Bing Photo of the Day'], [True, 16, u'High-resolution photos from Unsplash.com'], [True, 8, u"NASA's Astronomy Picture of the Day"], [False, 11, u'World Sunlight Map - live wallpaper from Die.net'], [True, 7, u'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;']]'
INFO: 2019-01-18 09:21:36,176: log_options() 'stats_enabled = True'
INFO: 2019-01-18 09:21:36,176: log_options() 'stats_notice_shown = True'
INFO: 2019-01-18 09:21:36,176: log_options() 'sync_enabled = True'
INFO: 2019-01-18 09:21:36,176: log_options() 'use_landscape_enabled = True'
INFO: 2019-01-18 09:21:36,176: reload_config() 'No need to clear prepared queue'
INFO: 2019-01-18 09:21:36,177: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 300'
INFO: 2019-01-18 09:21:36,177: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/Bing/UKSomerset_EN-US2145655784_1920x1080.jpg'
INFO: 2019-01-18 09:21:36,184: regular_change_thread() 'regular_change thread running'
INFO: 2019-01-18 09:21:36,185: prepare_thread() 'Prepare thread running'
INFO: 2019-01-18 09:21:36,185: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2019-01-18 09:21:36,185: prepare_thread() 'Preparing some images'
INFO: 2019-01-18 09:21:36,232: _run() 'sync: Started, hash fbe1129bb95449547552e6be2da39120'
INFO: 2019-01-18 09:21:36,233: load_user() 'smart: Missing smart_user.json, creating new smart user'
INFO: 2019-01-18 09:21:36,233: new_user() 'smart: Creating new smart user'
INFO: 2019-01-18 09:21:36,235: update_indicator_icon() 'Creating indicator'
INFO: 2019-01-18 09:21:36,307: do_set_wp() 'Calling do_set_wp with /home/fuzie/.config/variety/Downloaded/Bing/UKSomerset_EN-US2145655784_1920x1080.jpg, time: 1547799696.31'
ERROR: 2019-01-18 09:21:36,310: _run() 'sync: Could not load or create smart user'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 516, in _run
    self.load_user(create_if_missing=True)
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 128, in load_user
    self.new_user()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 136, in new_user
    self.user = Util.fetch_json(Smart.API_URL + '/newuser')
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/newuser (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe98835c790>: Failed to establish a new connection: [Errno -2] Name or service not known',))
WARNING: 2019-01-18 09:21:36,332: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2019-01-18 09:21:36,333: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/Bing/UKSomerset_EN-US2145655784_1920x1080.jpg'
INFO: 2019-01-18 09:21:36,348: set_icon() 'Showing indicator icon image: /home/fuzie/.config/variety/Downloaded/Bing/UKSomerset_EN-US2145655784_1920x1080.jpg'
INFO: 2019-01-18 09:21:36,349: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/Bing/UKSomerset_EN-US2145655784_1920x1080.jpg'
INFO: 2019-01-18 09:21:36,381: prepare_thread() 'After search prepared buffer contains 93 images'
INFO: 2019-01-18 09:21:36,431: set_icon() 'Showing indicator icon image: /home/fuzie/.config/variety/Downloaded/Bing/UKSomerset_EN-US2145655784_1920x1080.jpg'
INFO: 2019-01-18 09:21:37,674: reload() 'Reloading preferences dialog'
INFO: 2019-01-18 09:21:37,679: load_user() 'smart: Missing smart_user.json, creating new smart user'
INFO: 2019-01-18 09:21:37,679: new_user() 'smart: Creating new smart user'
INFO: 2019-01-18 09:21:37,682: load_user() 'smart: Missing smart_user.json, creating new smart user'
INFO: 2019-01-18 09:21:37,682: new_user() 'smart: Creating new smart user'
INFO: 2019-01-18 09:21:37,695: load_user() 'smart: Missing smart_user.json, creating new smart user'
INFO: 2019-01-18 09:21:37,695: new_user() 'smart: Creating new smart user'
INFO: 2019-01-18 09:21:37,699: _run() 'sync: Started, hash 935f06d81f647c6fe8e87a634609d8db'
INFO: 2019-01-18 09:21:37,699: load_user() 'smart: Missing smart_user.json, creating new smart user'
INFO: 2019-01-18 09:21:37,700: new_user() 'smart: Creating new smart user'
ERROR: 2019-01-18 09:21:37,702: _run() 'sync: Could not load or create smart user'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 516, in _run
    self.load_user(create_if_missing=True)
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 128, in load_user
    self.new_user()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 136, in new_user
    self.user = Util.fetch_json(Smart.API_URL + '/newuser')
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/newuser (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe9541d32d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:21:38,336: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/Bing/UKSomerset_EN-US2145655784_1920x1080.jpg'
INFO: 2019-01-18 09:21:56,194: stats_report_config() 'Stats: Reporting config anonymously'
ERROR: 2019-01-18 09:21:56,209: reporting_thread_method() 'Stats: Could not report config'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 999, in reporting_thread_method
    self.smart.stats_report_config()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 851, in stats_report_config
    res = Util.fetch_json(Smart.API_URL + '/stats/%s/report-config' % statsid, data=data)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/stats/3f5st6qwa8/report-config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe954122950>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:21:56,229: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-01-18 09:21:56,232: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 979, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9541d3210>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:22:26,238: stats_report_config() 'Stats: Reporting config anonymously'
ERROR: 2019-01-18 09:22:26,241: reporting_thread_method() 'Stats: Could not report config'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 999, in reporting_thread_method
    self.smart.stats_report_config()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 851, in stats_report_config
    res = Util.fetch_json(Smart.API_URL + '/stats/%s/report-config' % statsid, data=data)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/stats/3f5st6qwa8/report-config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe9541abad0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:22:26,258: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-01-18 09:22:26,260: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 979, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe9541ab810>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:22:56,263: stats_report_config() 'Stats: Reporting config anonymously'
ERROR: 2019-01-18 09:22:56,276: reporting_thread_method() 'Stats: Could not report config'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 999, in reporting_thread_method
    self.smart.stats_report_config()
  File "/usr/lib/python2.7/dist-packages/variety/Smart.py", line 851, in stats_report_config
    res = Util.fetch_json(Smart.API_URL + '/stats/%s/report-config' % statsid, data=data)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='vrty.org', port=443): Max retries exceeded with url: /api/stats/3f5st6qwa8/report-config (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe95418d710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:22:56,289: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-01-18 09:22:56,297: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 979, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe954122490>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:23:26,324: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-01-18 09:23:26,331: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 979, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe988103790>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:23:56,361: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-01-18 09:23:56,368: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 979, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 506, in request
    verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe988114c10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
INFO: 2019-01-18 09:26:36,177: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-01-18 09:26:36,177: set_wallpaper() 'Calling set_wallpaper with /home/fuzie/.config/variety/Downloaded/Desktoppr/297.jpg'
INFO: 2019-01-18 09:26:36,177: prepare_thread() 'Prepared buffer contains 92 images'
INFO: 2019-01-18 09:26:36,178: do_set_wp() 'Calling do_set_wp with /home/fuzie/.config/variety/Downloaded/Desktoppr/297.jpg, time: 1547799996.18'
INFO: 2019-01-18 09:26:36,209: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/Desktoppr/297.jpg'
INFO: 2019-01-18 09:26:36,314: set_icon() 'Showing indicator icon image: /home/fuzie/.config/variety/Downloaded/Desktoppr/297.jpg'
INFO: 2019-01-18 09:31:36,217: purge_downloaded() 'Refreshed download folder size: 449 mb'
INFO: 2019-01-18 09:31:36,219: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-01-18 09:31:36,314: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-01-18 09:31:36,315: set_wallpaper() 'Calling set_wallpaper with /home/fuzie/Dropbox/Andet/Favorites/4K Brooklyn Bridge.jpg'
INFO: 2019-01-18 09:31:36,315: prepare_thread() 'Prepared buffer contains 91 images'
INFO: 2019-01-18 09:31:36,317: do_set_wp() 'Calling do_set_wp with /home/fuzie/Dropbox/Andet/Favorites/4K Brooklyn Bridge.jpg, time: 1547800296.32'
INFO: 2019-01-18 09:31:36,397: update_indicator() 'Setting file info to: /home/fuzie/Dropbox/Andet/Favorites/4K Brooklyn Bridge.jpg'
INFO: 2019-01-18 09:31:36,639: set_icon() 'Showing indicator icon image: /home/fuzie/Dropbox/Andet/Favorites/4K Brooklyn Bridge.jpg'
ERROR: 2019-01-18 09:31:38,739: download_thread() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 1039, in download_thread
    self.download_one_from(downloader)
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 1071, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python2.7/dist-packages/variety/DesktopprDownloader.py", line 35, in download_one
    response = Util.fetch_json(self.location)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 507, in request
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 502 Server Error: Bad Gateway for url: https://api.desktoppr.co/1/wallpapers/random
INFO: 2019-01-18 09:36:36,639: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-01-18 09:36:36,640: set_wallpaper() 'Calling set_wallpaper with /home/fuzie/.config/variety/Downloaded/Desktoppr/151112mclarb.jpg'
INFO: 2019-01-18 09:36:36,640: prepare_thread() 'Prepared buffer contains 90 images'
INFO: 2019-01-18 09:36:36,641: do_set_wp() 'Calling do_set_wp with /home/fuzie/.config/variety/Downloaded/Desktoppr/151112mclarb.jpg, time: 1547800596.64'
INFO: 2019-01-18 09:36:36,690: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/Desktoppr/151112mclarb.jpg'
INFO: 2019-01-18 09:36:36,836: set_icon() 'Showing indicator icon image: /home/fuzie/.config/variety/Downloaded/Desktoppr/151112mclarb.jpg'
INFO: 2019-01-18 09:41:36,194: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-01-18 09:41:36,836: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-01-18 09:41:36,837: set_wallpaper() 'Calling set_wallpaper with /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527885988_9a480cb101_o.jpg'
INFO: 2019-01-18 09:41:36,837: prepare_thread() 'Prepared buffer contains 89 images'
INFO: 2019-01-18 09:41:36,840: do_set_wp() 'Calling do_set_wp with /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527885988_9a480cb101_o.jpg, time: 1547800896.84'
INFO: 2019-01-18 09:41:36,865: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527885988_9a480cb101_o.jpg'
INFO: 2019-01-18 09:41:36,984: set_icon() 'Showing indicator icon image: /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527885988_9a480cb101_o.jpg'
ERROR: 2019-01-18 09:41:38,509: download_thread() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 1039, in download_thread
    self.download_one_from(downloader)
  File "/usr/lib/python2.7/dist-packages/variety/VarietyWindow.py", line 1071, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python2.7/dist-packages/variety/DesktopprDownloader.py", line 35, in download_one
    response = Util.fetch_json(self.location)
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 529, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python2.7/dist-packages/variety/Util.py", line 507, in request
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 502 Server Error: Bad Gateway for url: https://api.desktoppr.co/1/wallpapers/random
INFO: 2019-01-18 09:46:36,985: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-01-18 09:46:36,986: set_wallpaper() 'Calling set_wallpaper with /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527966952_aa5f5077fc_o.jpg'
INFO: 2019-01-18 09:46:36,986: prepare_thread() 'Prepared buffer contains 88 images'
INFO: 2019-01-18 09:46:36,988: do_set_wp() 'Calling do_set_wp with /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527966952_aa5f5077fc_o.jpg, time: 1547801196.99'
INFO: 2019-01-18 09:46:37,060: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527966952_aa5f5077fc_o.jpg'
INFO: 2019-01-18 09:46:37,161: set_icon() 'Showing indicator icon image: /home/fuzie/.config/variety/Downloaded/flickr_user_www_flickr_com_photos_peter_levi__user_id_93647178_N00_/7527966952_aa5f5077fc_o.jpg'
INFO: 2019-01-18 09:51:36,195: parse_server_options() 'Unsplash.com: parsing serverside options'
ERROR: 2019-01-18 09:51:36,195: parse_server_options() 'Could not parse Unsplash.com serverside options, using defaults 0, 0'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/variety/Downloader.py", line 139, in parse_server_options
    options = self.parent.server_options[key]
KeyError: 'unsplash'
INFO: 2019-01-18 09:51:36,201: download_one() 'Downloading an image from Unsplash'
INFO: 2019-01-18 09:51:36,201: download_one() 'Queue size: 0'
INFO: 2019-01-18 09:51:36,202: fill_queue() 'Filling Unsplash queue from https://api.unsplash.com/photos/?page=89&per_page=30&client_id=072e5048dfcb73a8d9ad59fcf402471518ff8df725df462b0c4fa665f466515a'
INFO: 2019-01-18 09:51:36,716: fill_queue() 'Unsplash populated with 14 URLs'
INFO: 2019-01-18 09:51:36,717: save_locally() 'Origin URL: https://unsplash.com/photos/FjW6gydTHBw'
INFO: 2019-01-18 09:51:36,718: save_locally() 'Image URL: https://unsplash.com/photos/FjW6gydTHBw/download'
INFO: 2019-01-18 09:51:36,718: save_locally() 'Local name: /home/fuzie/.config/variety/Downloaded/Unsplash/FjW6gydTHBw.jpg'
INFO: 2019-01-18 09:51:37,161: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-01-18 09:51:37,161: set_wallpaper() 'Calling set_wallpaper with /home/fuzie/Dropbox/Andet/Favorites/wallhaven-65308.jpg'
INFO: 2019-01-18 09:51:37,161: prepare_thread() 'Prepared buffer contains 87 images'
INFO: 2019-01-18 09:51:37,162: do_set_wp() 'Calling do_set_wp with /home/fuzie/Dropbox/Andet/Favorites/wallhaven-65308.jpg, time: 1547801497.16'
INFO: 2019-01-18 09:51:37,194: update_indicator() 'Setting file info to: /home/fuzie/Dropbox/Andet/Favorites/wallhaven-65308.jpg'
INFO: 2019-01-18 09:51:37,310: set_icon() 'Showing indicator icon image: /home/fuzie/Dropbox/Andet/Favorites/wallhaven-65308.jpg'
INFO: 2019-01-18 09:51:38,647: save_locally() 'Download complete'
INFO: 2019-01-18 09:51:38,647: update_indicator() 'Setting file info to: /home/fuzie/Dropbox/Andet/Favorites/wallhaven-65308.jpg'
INFO: 2019-01-18 09:51:38,648: download_one_from() 'Adding downloaded file /home/fuzie/.config/variety/Downloaded/Unsplash/FjW6gydTHBw.jpg to prepared_from_downloads queue'
INFO: 2019-01-18 09:56:37,310: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2019-01-18 09:56:37,311: set_wallpaper() 'Calling set_wallpaper with /home/fuzie/.config/variety/Downloaded/Unsplash/FjW6gydTHBw.jpg'
INFO: 2019-01-18 09:56:37,312: prepare_thread() 'Prepared buffer contains 87 images'
INFO: 2019-01-18 09:56:37,314: do_set_wp() 'Calling do_set_wp with /home/fuzie/.config/variety/Downloaded/Unsplash/FjW6gydTHBw.jpg, time: 1547801797.31'
INFO: 2019-01-18 09:56:37,392: update_indicator() 'Setting file info to: /home/fuzie/.config/variety/Downloaded/Unsplash/FjW6gydTHBw.jpg'
INFO: 2019-01-18 09:56:37,681: set_icon() 'Showing indicator icon image: /home/fuzie/.config/variety/Downloaded/Unsplash/FjW6gydTHBw.jpg'
